/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentificare utilizator
         * @description Verifică credențialele și returnează un token JWT care conține rolul utilizatorului (STUDENT, ORGANIZER, ADMIN).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credențialele de acces (email instituțional recomandat). */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login reușit. Returnează token-ul și datele de bază ale profilului. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Înregistrare cont nou
         * @description Creează un cont nou de tip STUDENT. Rolurile superioare se acordă manual de către Admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Datele necesare pentru crearea contului. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Cont creat cu succes. Utilizatorul poate face login imediat. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/associations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listare asociații
         * @description Returnează lista tuturor asociațiilor active. Folosit pentru popularea dropdown-urilor de filtrare din Frontend.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista completă de asociații (format simplificat). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssociationSimple"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/associations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalii publice asociație
         * @description Afișează profilul public al unei asociații (descriere, contact, link-uri social media).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul unic al asociației (UUID). */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profilul detaliat al asociației. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssociationDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listare Evenimente (Public)
         * @description Endpoint-ul principal pentru Feed-ul de evenimente.  Returnează o listă paginată de carduri (EventPreview). Dacă request-ul conține un token valid, câmpul `isRegistered` va fi calculat pentru fiecare eveniment.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Obiect complex de filtrare (search, dată, tip, asociație etc.) "explodat" în parametri URL. */
                    filters?: components["schemas"]["EventFilterQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rezultatele căutării (paginated). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["EventPreview"][];
                            /** @description Numărul total de rezultate pentru paginare. */
                            total?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * (Organizator) Propune Eveniment Nou
         * @description Creează un eveniment în starea PENDING. Necesită rol de ORGANIZER. Include detalii logistice, imagini și agendă.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Datele complete ale evenimentului propus. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventCreateRequest"];
                };
            };
            responses: {
                /** @description Eveniment creat cu succes. Așteaptă aprobare. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evenimente Recomandate
         * @description Returnează o listă de evenimente bazată pe preferințele setate în profilul utilizatorului (tag-uri, facultate)  și istoricul participărilor anterioare.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de recomandări personalizate. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventPreview"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID-ul evenimentului. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Detalii complete eveniment
         * @description Returnează toate informațiile despre un eveniment (inclusiv descriere lungă, agendă, galerie). Dacă userul e logat, verifică statusul înscrierii.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Obiectul complet al evenimentului. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventResponse"];
                    };
                };
            };
        };
        /**
         * (Organizator) Editare eveniment
         * @description Permite modificarea detaliilor unui eveniment existent. Doar creatorul sau un Admin poate face asta.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EventCreateRequest"];
                };
            };
            responses: {
                /** @description Eveniment actualizat cu succes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * (Organizator/Admin) Ștergere
         * @description Șterge (sau marchează ca șters - soft delete) un eveniment.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eveniment șters. Nu returnează conținut. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID-ul evenimentului de moderat. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * (Admin) Aprobare/Respingere
         * @description Endpoint pentru fluxul de moderare. Adminul aprobă publicarea sau respinge (cu motiv).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului de moderat. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        status?: components["schemas"]["EnumEventStatus"];
                        /** @description Obligatoriu dacă statusul este REJECTED. */
                        rejectionReason?: string;
                    };
                };
            };
            responses: {
                /** @description Status actualizat. Evenimentul devine vizibil (sau ascuns). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/events/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID-ul evenimentului. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * (Organizator) Listă Participanți & Export
         * @description Returnează lista studenților înscriși. Dacă parametrul `format` este specificat, returnează un fișier (CSV/PDF) pentru descărcare.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Formatul dorit. Dacă lipsește, returnează JSON. */
                    format?: components["schemas"]["EnumExportFormat"];
                };
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Date JSON sau Stream de fișier (Content-Disposition attachment). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID-ul evenimentului. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Vezi recenziile
         * @description Listează feedback-ul public pentru acest eveniment.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de recenzii. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Adaugă Recenzie
         * @description Permite unui participant (care a fost prezent sau înscris) să lase o notă și un comentariu.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul evenimentului. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReviewCreate"];
                };
            };
            responses: {
                /** @description Recenzie adăugată cu succes. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Biletele mele
         * @description Returnează istoricul înscrierilor utilizatorului curent (Portofel virtual).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de bilete active și trecute. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Înscriere (JOIN)
         * @description Înscrie utilizatorul curent la un eveniment.  Generează un bilet unic și un QR code.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description ID-ul evenimentului la care se face înscrierea.
                         */
                        eventId?: string;
                    };
                };
            };
            responses: {
                /** @description Înscriere reușită. Returnează datele biletului. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketResponse"];
                    };
                };
                /** @description Eroare - Utilizator deja înscris SAU Locuri epuizate. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalii bilet
         * @description Returnează detaliile unui singur bilet, util pentru afișarea QR code-ului pe tot ecranul.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detalii bilet. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-in/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validare bilet (Scanare QR)
         * @description Utilizat de organizatori la intrare.  Primește conținutul scanat din QR, îl decriptează/validează și marchează biletul ca CHECKED_IN.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CheckInRequest"];
                };
            };
            responses: {
                /** @description Rezultatul validării (Succes sau Eroare). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True dacă accesul este permis. */
                            valid?: boolean;
                            /** @description Mesaj pentru operator (ex: 'Acces Permis', 'Bilet deja scanat'). */
                            message?: string;
                            /** @description Numele studentului pentru verificare vizuală. */
                            studentName?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datele mele
         * @description Returnează profilul utilizatorului logat, inclusiv datele academice și preferințele.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profil utilizator. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
            };
        };
        /**
         * Actualizare Profil
         * @description Permite modificarea preferințelor și a datelor academice (Facultate, Departament).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            responses: {
                /** @description Profil actualizat cu succes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Admin) Rapoarte
         * @description Returnează statistici globale despre utilizarea platformei (nr. evenimente, participare, top asociații).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Obiect cu statistici agregate. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Rolul utilizatorului în sistem.
         * @enum {string}
         */
        EnumUserRole: "STUDENT" | "ORGANIZER" | "ADMIN";
        /**
         * @description Statusul tehnic din baza de date (Ciclul de viață complet).
         * @enum {string}
         */
        EnumEventStatus: "DRAFT" | "PENDING" | "PUBLISHED" | "REJECTED" | "CANCELLED" | "COMPLETED";
        /**
         * @description Status calculat pentru afișare în UI, bazat pe timp și starea internă.
         * @enum {string}
         */
        EnumPublicStatus: "UPCOMING" | "ONGOING" | "ENDED" | "CANCELLED";
        /**
         * @description Categoria principală a evenimentului.
         * @enum {string}
         */
        EnumEventType: "ACADEMIC" | "SOCIAL" | "SPORTS" | "CAREER" | "VOLUNTEERING" | "WORKSHOP";
        /**
         * @description Clasificarea locației pentru filtrare rapidă.
         * @enum {string}
         */
        EnumLocationType: "IN_CAMPUS" | "IN_CITY" | "OUTSIDE_CITY" | "ONLINE";
        /**
         * @description Starea curentă a biletului unui student.
         * @enum {string}
         */
        EnumTicketStatus: "CONFIRMED" | "CHECKED_IN" | "CANCELLED";
        /**
         * @description Formatele suportate pentru exportul listelor.
         * @enum {string}
         */
        EnumExportFormat: "json" | "csv" | "pdf";
        /**
         * @description Tipul entității organizatoare (Instituțională vs Studențească).
         * @enum {string}
         */
        EnumOrganizerType: "STUDENT_ORG" | "UNIVERSITY_DEPT" | "COMPANY" | "OTHER";
        /** @description Un element din orarul (timeline-ul) evenimentului. */
        AgendaItem: {
            /**
             * @description Intervalul orar.
             * @example 10:00 - 11:30
             */
            time?: string;
            /**
             * @description Titlul activității.
             * @example Keynote Speaker
             */
            title?: string;
            /** @description Detalii suplimentare despre activitate. */
            description?: string;
            /**
             * @description Lista persoanelor care vorbesc (dacă e cazul).
             * @example [
             *       "Dr. Popescu"
             *     ]
             */
            speakers?: string[];
        };
        /** @description Colecție de link-uri externe ale asociației. */
        SocialLinks: {
            /** Format: uri */
            website?: string;
            /** Format: uri */
            instagram?: string;
            /** Format: uri */
            facebook?: string;
            /** Format: uri */
            linkedin?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example student@usv.ro
             */
            email: string;
            /** Format: password */
            password: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description Email instituțional.
             */
            email: string;
            /** Format: password */
            password: string;
            /** @example Ion Popescu */
            fullName: string;
            /** @description Facultatea de apartenență (Opțional la înregistrare). */
            faculty?: string;
        };
        AuthResponse: {
            /** @description JWT Token pentru autentificare la request-urile viitoare. */
            token?: string;
            user?: components["schemas"]["UserProfile"];
        };
        /** @description Datele complete ale profilului utilizator. */
        UserProfile: {
            /** Format: uuid */
            id?: string;
            email?: string;
            fullName?: string;
            role?: components["schemas"]["EnumUserRole"];
            faculty?: string;
            department?: string;
            /** @description Lista categoriilor de interes pentru utilizator. */
            preferences?: components["schemas"]["EnumEventType"][];
        };
        /** @description Versiune simplificată a asociației, pentru liste și referințe. */
        AssociationSimple: {
            /** Format: uuid */
            id?: string;
            name?: string;
            logoUrl?: string;
            type?: components["schemas"]["EnumOrganizerType"];
        };
        AssociationDetail: components["schemas"]["AssociationSimple"] & {
            description?: string;
            contactEmail?: string;
            socialLinks?: components["schemas"]["SocialLinks"];
        };
        /** @description DTO pentru crearea sau editarea unui eveniment. */
        EventCreateRequest: {
            /** @description Lista ID-urilor asociațiilor organizatoare. */
            organizerIds: string[];
            title: string;
            description?: string;
            type?: components["schemas"]["EnumEventType"];
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            /** @description Numele locației (ex: 'Corp C'). */
            locationName: string;
            locationType?: components["schemas"]["EnumLocationType"];
            /** @description Imaginea principală (Banner). */
            coverImageUrl?: string;
            /** @description Link-uri către alte imagini. */
            galleryImageUrls?: string[];
            /** @description Lista de activități din cadrul evenimentului. */
            agenda?: components["schemas"]["AgendaItem"][];
        };
        /** @description Versiune redusă a evenimentului, optimizată pentru afișarea în liste și carduri. */
        EventPreview: {
            /** Format: uuid */
            id?: string;
            title?: string;
            coverImageUrl?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            locationName?: string;
            status?: components["schemas"]["EnumPublicStatus"];
            organizers?: components["schemas"]["AssociationSimple"][];
            /** @description Dacă true, utilizatorul curent (din token) este deja înscris. */
            isRegistered?: boolean;
        };
        EventResponse: components["schemas"]["EventPreview"] & {
            description?: string;
            type?: components["schemas"]["EnumEventType"];
            locationType?: components["schemas"]["EnumLocationType"];
            currentParticipants?: number;
            galleryImageUrls?: string[];
            agenda?: components["schemas"]["AgendaItem"][];
        };
        /** @description Biletul digital al studentului. */
        TicketResponse: {
            /** Format: uuid */
            id?: string;
            eventTitle?: string;
            /** Format: date-time */
            eventStartAt?: string;
            /** @description String criptat pentru generarea codului QR vizual. */
            qrCodeContent?: string;
            status?: components["schemas"]["EnumTicketStatus"];
        };
        CheckInRequest: {
            /** @description Conținutul citit de scanner. */
            qrContent: string;
            /** Format: uuid */
            eventId: string;
        };
        ReviewCreate: {
            rating: number;
            comment?: string;
        };
        ReviewResponse: components["schemas"]["ReviewCreate"] & {
            /** Format: uuid */
            id?: string;
            userName?: string;
            /** Format: date-time */
            createdAt?: string;
            authorTicketStatus?: components["schemas"]["EnumTicketStatus"] & unknown;
        };
        /** @description Filtre avansate. Câmpurile array permit selecție multiplă (OR logic implicit, dacă nu se specifică altfel). */
        EventFilterQuery: {
            /** @default 1 */
            page: number;
            /** @default 20 */
            limit: number;
            /** @description Căutare text (titlu, descriere) */
            search?: string;
            /** @description Lista tipurilor selectate (ex: [SOCIAL, SPORTS]) */
            types?: components["schemas"]["EnumEventType"][];
            /**
             * @description Flag pentru logica de filtrare a tipurilor: - FALSE (Default): Returnează evenimentele care sunt de tip A **SAU** B. - TRUE: Returnează evenimentele care sunt și A **ȘI** B.
             * @default false
             */
            matchAllTypes: boolean;
            /** @description Selectare asociații specifice (ex: doar evenimentele ASUS și OSF) */
            associationIds?: string[];
            /** @description Filtrare după natura organizatorului */
            organizerTypes?: components["schemas"]["EnumOrganizerType"][];
            /** @description Selectare multiplă (ex: IN_CAMPUS + IN_CITY) */
            locationTypes?: components["schemas"]["EnumLocationType"][];
            /** @description Lista facultăților selectate (ex: ['FIESC', 'FEAA']) */
            faculties?: string[];
            /** @description Lista departamentelor selectate */
            departments?: string[];
            /** Format: date-time */
            dateFrom?: string;
            /** Format: date-time */
            dateTo?: string;
            /** @description [PROTEJAT] Permite filtrarea după starea tehnică. - Studenții: Ignorat (backend-ul forțează PUBLISHED). - Organizatori: Pot cere DRAFT, PENDING, REJECTED pentru asociația lor. - Adminii: Pot cere PENDING pentru a vedea coada de aprobare. */
            status?: components["schemas"]["EnumEventStatus"][];
        };
        AdminReport: {
            totalEvents?: number;
            totalRegistrations?: number;
            attendanceRate?: number;
            topAssociations?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
